Name : Rojen Dangol

ID   : 2357811

In [5]:
import pandas as pd

dataset = pd.read_csv('/content/drive/MyDrive/Copy of Titanic-Dataset.csv')

In [6]:
df = pd.DataFrame(dataset)

1. Create a DataFrame called fare that contains only the Fare column of the Titanic dataset. Print the
head of the result.

In [7]:
df_fare= df['Fare']
df_fare.head()

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

2. Create a DataFrame called class age that contains only the Pclass and Age columns of the Titanic
dataset, in that order. Print the head of the result.

In [8]:
df_class = df[["Pclass","Age"]]
df_class.head()

   Pclass   Age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0

3. Create a DataFrame called survived gender that contains the Survived and Sex columns of the
Titanic dataset, in that order.Print the head of the result.

In [9]:
survived_gender = df[["Survived","Sex"]]
survived_gender.head()

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

Problem - 2 - Subsetting:
Complete all the following Task:
Subsetting Rows:
1. Filter the Titanic dataset for cases where the passenger’s fare is greater than 100, assigning it
to fare gt 100.View the printed result.

In [10]:
fare_gt_100 = df[df['Fare'] > 100]
fare_gt_100.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C

2. Filter the Titanic dataset for cases where the passenger’s class (Pclass) is 1, assigning it to
first class.View the printed result.

In [11]:
first_class = df[df['Pclass'] == 1]
first_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

3. Filter the Titanic dataset for cases where the passenger’s age is less than 18 and the passenger
is female (Sex is "female"), assigning it to female under 18. View the printed result.

In [12]:
female_under_18 = df[(df['Age'] < 18) & (df['Sex'] == 'female')]
female_under_18.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S

Subsetting Rows by Categorical variables:
1. Filter the Titanic dataset for passengers whose Embarked port is either "C" (Cherbourg) or "S"
(Southampton), assigning the result to embarked c or s. View the printed result.

In [13]:
embarked_c_or_s = df[(df['Embarked'] == 'C') | (df['Embarked'] == 'S')]
embarked_c_or_s.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

2. Filter the Titanic dataset for passengers whose Pclass is in the list [1, 2] (indicating first
or second class), assigning the result to first second class.View the printed result.

In [14]:
first_second_class = df[df['Pclass'].isin([1, 2])]
first_second_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

3.2 Exercise - 1.
Warning: Handle missing values in the Age column by filling them with the median age of the dataset before performing the division.

Which passenger had the highest fare paid relative to their age?

To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per year, containing the fare divided by the age of
the passenger(i.e., Fare/Age).

In [15]:
df['Fare_per_year'] = df['Fare'] / df['Age']
df['Fare_per_year'].head()

0    0.329545
1    1.875876
2    0.304808
3    1.517143
4    0.230000
Name: Fare_per_year, dtype: float64

2. Subset rows where fare per year is higher than 5, assigning this to high fare age.

In [16]:
df_high_fare_age = df[df['Fare_per_year'] > 5]
df_high_fare_age.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_per_year
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,10.537500
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,14.562500
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,13.842105
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C,13.859733
50,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S,5.669643

3. Sort high fare age by descending fare per year, assigning this to high fare age srt.

In [17]:
df_descending_fare_per_year = df_high_fare_age.sort_values(by='Fare_per_year', ascending=False)
df_descending_fare_per_year.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_per_year
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,164.728261
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,75.775000
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S,46.900000
164,165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S,39.687500
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S,39.000000

4. Select only the Name and fare per year columns of high fare age srt and save the result as result.
5. Look at the result.

In [18]:
df_result = df_descending_fare_per_year[['Name', 'Fare_per_year']]
df_result.head()

                                Name  Fare_per_year
305   Allison, Master. Hudson Trevor     164.728261
297     Allison, Miss. Helen Loraine      75.775000
386  Goodwin, Master. Sidney Leonard      46.900000
164     Panula, Master. Eino Viljami      39.687500
183        Becker, Master. Richard F      39.000000

Which adult male passenger (age ≥ 18 and Sex is ’male’) paid the highest fare relative to their
class?
To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per class, containing the fare divided by the passenger
class i.e. Fare / Pclass.

In [19]:
df['Fare_per_class'] = df['Fare'] / df['Pclass']
df['Fare_per_class'].head()

0     2.416667
1    71.283300
2     2.641667
3    53.100000
4     2.683333
Name: Fare_per_class, dtype: float64

2. Subset rows where the passenger is male (Sex is ”male”) and an adult (Age is greater than or equal
to 18), assigning this to adult males.

3. Sort adult males by descending fare per class, assigning this to adult males srt.

In [20]:
df_male_above_18 = df[(df['Sex'] == 'male') & (df['Age'] >= 18)]
adult_males_srt = df_male_above_18.sort_values(by='Fare_per_class', ascending=False)
adult_males_srt.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_per_year,Fare_per_class
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,14.637977,512.3292
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,14.231367,512.3292
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,13.842105,263.0000
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,4.109375,263.0000
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C,10.313367,247.5208


4. Select only the Name, Age, and fare per class columns of adult males sr and save the result
as result.
5. Look at the result.

In [21]:
result = adult_males_srt[['Name', 'Age', 'Fare_per_class']]
result.head()

                                   Name   Age  Fare_per_class
737              Lesurer, Mr. Gustave J  35.0        512.3292
679  Cardeza, Mr. Thomas Drake Martinez  36.0        512.3292
27       Fortune, Mr. Charles Alexander  19.0        263.0000
438                   Fortune, Mr. Mark  64.0        263.0000
118            Baxter, Mr. Quigg Edmond  24.0        247.5208

What percent of the total fare revenue came from each passenger class?
To answer the question perform following operation:
1. Calculate the total Fare paid across all passengers in the Titanic dataset.

In [24]:
total_fare = df['Fare'].sum()
total_fare

28693.9493

2. Subset for passengers in first class (Pclass is 1) and calculate their total fare.

In [25]:
first_class_fare = df[df['Pclass'] == 1]['Fare'].sum()
first_class_fare

18177.4125

3. Do the same for second class (Pclass is 2) and third class (Pclass is 3).

In [29]:
Second_class_fare = df[df['Pclass'] == 2]['Fare'].sum()
print("Second class fare")
Second_class_fare

Second class fare

3801.8417

In [30]:
third_class_fare = df[df['Pclass'] == 3]['Fare'].sum()
print("Third class fare")
third_class_fare

Third class fare

6714.6951

4. Combine the fare totals from first, second, and third classes into a list.

In [31]:
fare_totals = [first_class_fare, Second_class_fare, third_class_fare]
fare_totals

[18177.4125, 3801.8417, 6714.6951]

5. Divide the totals for each class by the overall total fare to get the proportion of fare revenue by class.

In [32]:
each_class_proportion = [total / total_fare for total in fare_totals]
each_class_proportion

[0.6334928771899656, 0.1324962855496507, 0.23401083726038366]

To answer the question perform following operation:
1. Create a new column, age group, that categorizes passengers into "child" (age < 18), "adult" (age
18{64), and "senior" (age 65 and above).

In [33]:
df['age_group'] = pd.cut(df['Age'], bins=[0, 18, 64, float('inf')], labels=['child', 'adult', 'senior'])
df['age_group']

0      adult
1      adult
2      adult
3      adult
4      adult
       ...
886    adult
887    adult
888      NaN
889    adult
890    adult
Name: age_group, Length: 891, dtype: category
Categories (3, object): ['child' < 'adult' < 'senior']

2. Calculate the total number of passengers on the Titanic.

In [36]:
total_no_of_passengers = len(df)
print("Total no of passengers: ")
total_no_of_passengers

Total no of passengers:

891


3. Count the number of passengers in each age group.

In [37]:
no_of_passengers_in_each_age_group = df['age_group'].value_counts()
no_of_passengers_in_each_age_group

age_group
adult     564
child     139
senior     11
Name: count, dtype: int64

4. Divide the count of each age group by the total number of passengers to get the proportion of passengers
in each age group.

In [38]:
age_group_proportion = no_of_passengers_in_each_age_group / total_no_of_passengers
age_group_proportion

age_group
adult     0.632997
child     0.156004
senior    0.012346
Name: count, dtype: float64

Display the proportion as a percentage.

In [39]:
age_group_proportion_percentage = age_group_proportion * 100
age_group_proportion_percentage

age_group
adult     63.299663
child     15.600449
senior     1.234568
Name: count, dtype: float64